test = {   'name': 'q5_1',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(quirky_numbers, np.ndarray) and len(quirky_numbers) == 5\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> int(quirky_numbers[0] * 10 ** 4 % 10 ** 3) == 801 # Try again!\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> int(quirky_numbers[1] * 10 ** 3 % 10 ** 3) == 855 # Try again!\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> int(quirky_numbers[2] * 10 % 10 ** 3) == 4 # Try again!\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> int(quirky_numbers[3] * 10 ** 3 % 10 ** 3) == 392 # Try again!\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> int(quirky_numbers[4] * 10 ** 3 % 10 ** 3) == 189 # Try again!\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
