test = {   'name': 'q7_8',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(ranked_seasons, np.ndarray)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> import numbers\n>>> all(isinstance(season, numbers.Integral) for season in ranked_seasons)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> len(ranked_seasons) == 31\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> int(ranked_seasons[-4] * 10 ** 3 % 7 ** 2) == 17 # Try again!\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
