test = {   'name': 'q3_2',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> isinstance(most_common_combo, list) and isinstance(least_common_combo[0], str) and isinstance(least_common_combo[1], float)\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> len(most_common_combo) == 2 and len(least_common_combo) == 2\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
