test = {   'name': 'q3_1',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> callable(calculate_interest) and calculate_interest(500) == .142\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> calculate_interest(500) in [.056, .069, .093, .119, .142] # Only return values from the table, which should all be less than 1\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
