test = {   'name': 'q2_2',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(convenience_stats, np.ndarray) and len(convenience_stats) == 2\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> int(convenience_stats[0] * 10 ** 3 % 10 ** 4) + int(convenience_stats[1] * 10 ** 5 % 10 ** 4) == 4432 # Try again!\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
