test = {   'name': 'q4_3',
    'points': None,
    'suites': [   {   'cases': [   {   'code': ">>> callable(city_and_hist) and (tokyo_string != None) # Make sure your function returns a string, and doesn't just print a string\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': ">>> tokyo_string[:65] == 'A 99% confidence interval for the average hotel price in Tokyo is'\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
